# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6d153b78f5620cdf7ef4795f7b81c95d3596ca799d369138b0afd00351d0c712e1b5343133bf054504b9a2f43a1adb34421914c1dc832b2ff92d38ea2191b4d

test:
  secret_key_base: fad6054023be0557697a6620b35d3e9a7e60ce0a55fe20011f455ad4c05418adefbfc66580a519dc5c0e85048470a91fa68fcb60228400aaed01f096cf79a3c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
